import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

export const ALL_LEADS_DATA = [
  {
    "serialNo": 1,
    "name": "K.M constructions",
    "projectType": "Turnkey Architecture & Construction",
    "projectDescription": "📍 Google Maps Listing: K.M constructions (Construction company)\n★ Rating: ⭐ 5 (30 reviews)\n🏢 Address: No 2, 10th Cross St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=K.M%20constructions&query_place_id=ChIJmxzHDUJhUjoRvPcbwEQhDoQ\n💡 Project: Turnkey Architecture & Construction",
    "location": "No 2, 10th Cross St, Chennai, Tamil Nadu",
    "budgetLakhs": 65,
    "source": "Google",
    "priority": "HOT",
    "phone": "8778273957",
    "email": "contact@kmconstructions.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 2,
    "name": "Rajalakshmi Constructions",
    "projectType": "Turnkey Architecture & Construction",
    "projectDescription": "📍 Google Maps Listing: Rajalakshmi Constructions (Construction company)\n★ Rating: ⭐ 5 (10 reviews)\n🏢 Address: 148, Radha Ave Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Rajalakshmi%20Constructions&query_place_id=ChIJa_W7cjdhUjoR0uIMhl1Q3hk\n💡 Project: Turnkey Architecture & Construction",
    "location": "148, Radha Ave Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 55,
    "source": "Google",
    "priority": "HOT",
    "phone": "9941525262",
    "email": "contact@rajalakshmicons.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 3,
    "name": "SPERANZA CONSTRUCTIONS, RENOVATION AND INTERIORS.",
    "projectType": "Luxury Interior Renovation & Architecture",
    "projectDescription": "📍 Google Maps Listing: SPERANZA CONSTRUCTIONS, RENOVATION AND INTERIORS. (Construction company)\n★ Rating: ⭐ 5 (33 reviews)\n🏢 Address: 2, First street, C.D.N. Nagar Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=SPERANZA%20CONSTRUCTIONS%2C%20RENOVATION%20AND%20INTERIORS.&query_place_id=ChIJB5uofZJhUjoRj7EnwRWcQWk\n💡 Project: Luxury Interior Renovation & Architecture",
    "location": "2, First street, C.D.N. Nagar Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 70,
    "source": "Google",
    "priority": "HOT",
    "phone": "9940888456",
    "email": "contact@speranzaconstru.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 4,
    "name": "RJ Constructions",
    "projectType": "Turnkey Architecture & Construction",
    "projectDescription": "📍 Google Maps Listing: RJ Constructions (Construction company)\n★ Rating: ⭐ 3.9 (8 reviews)\n🏢 Address: 1st Cross Street, 2nd Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=RJ%20Constructions&query_place_id=ChIJO1LpCG9hUjoRUI3XwwuGUfk\n💡 Project: Turnkey Architecture & Construction",
    "location": "1st Cross Street, 2nd Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 45,
    "source": "Google",
    "priority": "WARM",
    "phone": "8248791229",
    "email": "contact@rjconstructions.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 5,
    "name": "Blessed builders",
    "projectType": "Turnkey Architecture & Construction",
    "projectDescription": "📍 Google Maps Listing: Blessed builders (Construction company)\n★ Rating: ⭐ 5 (5 reviews)\n🏢 Address: Jayaram nagar, 1st St, Vanagaram, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Blessed%20builders&query_place_id=ChIJwxgxaWVhUjoRMxe01Wer9Kc\n💡 Project: Turnkey Architecture & Construction",
    "location": "Jayaram nagar, 1st St, Vanagaram, Tamil Nadu",
    "budgetLakhs": 50,
    "source": "Google",
    "priority": "HOT",
    "phone": "9710618807",
    "email": "contact@blessedbuilders.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Vanagaram\",\"Top Rated\"]"
  },
  {
    "serialNo": 6,
    "name": "Tharun Construction",
    "projectType": "Turnkey Architecture & Construction",
    "projectDescription": "📍 Google Maps Listing: Tharun Construction (Construction company)\n★ Rating: ⭐ 4.2 (9 reviews)\n🏢 Address: 2nd Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Tharun%20Construction&query_place_id=ChIJKdPhcTRhUjoRJgXxdEb3iy0\n💡 Project: Turnkey Architecture & Construction",
    "location": "2nd Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 48,
    "source": "Google",
    "priority": "WARM",
    "phone": "9087888402",
    "email": "contact@tharunconstruct.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 7,
    "name": "R.K.CONSTRUCTION",
    "projectType": "Turnkey Architecture & Construction",
    "projectDescription": "📍 Google Maps Listing: R.K.CONSTRUCTION (Construction company)\n★ Rating: ⭐ 3.8 (4 reviews)\n🏢 Address: NO.5, R.K.BAVANAM, 7TH STREET IYYAPPA NAGAR, MADURAVOYAL, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=R.K.CONSTRUCTION&query_place_id=ChIJAYR7PlZhUjoRmyBs4uV7pok\n💡 Project: Turnkey Architecture & Construction",
    "location": "NO.5, R.K.BAVANAM, 7TH STREET IYYAPPA NAGAR, MADURAVOYAL, Chennai, Tamil Nadu",
    "budgetLakhs": 52,
    "source": "Google",
    "priority": "WARM",
    "phone": "9840324264",
    "email": "contact@rkconstruction.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 8,
    "name": "Krishna Builders",
    "projectType": "Turnkey Architecture & Construction",
    "projectDescription": "📍 Google Maps Listing: Krishna Builders (Construction company)\n★ Rating: ⭐ 5 (1 reviews)\n🏢 Address: 36, 1st Cross St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Krishna%20Builders&query_place_id=ChIJn9iDHT9hUjoRKDDFnvRJcj0\n💡 Project: Turnkey Architecture & Construction",
    "location": "36, 1st Cross St, Chennai, Tamil Nadu",
    "budgetLakhs": 60,
    "source": "Google",
    "priority": "HOT",
    "phone": "9840073239",
    "email": "contact@krishnabuilders.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 9,
    "name": "Blue Well Restaurant",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Blue Well Restaurant (Restaurant)\n★ Rating: ⭐ 4.9 (112 reviews)\n🏢 Address: 32, Alapakkam Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Blue%20Well%20Restaurant&query_place_id=ChIJWdUsFONhUjoRr9bOsUc3-uM\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "32, Alapakkam Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 35,
    "source": "Google",
    "priority": "HOT",
    "phone": "9360931010",
    "email": "contact@bluewellrestaur.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Restaurant\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 10,
    "name": "The Madras cafe's",
    "projectType": "Commercial Dining & Cafe Design",
    "projectDescription": "📍 Google Maps Listing: The Madras cafe's (Family restaurant)\n★ Rating: ⭐ 4.9 (18 reviews)\n🏢 Address: 6, Chokkanathar St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=The%20Madras%20cafe%27s&query_place_id=ChIJ23o7SQBhUjoRNwIYZaoPR9Q\n💡 Project: Commercial Dining & Cafe Design",
    "location": "6, Chokkanathar St, Chennai, Tamil Nadu",
    "budgetLakhs": 28,
    "source": "Google",
    "priority": "HOT",
    "phone": "7530001484",
    "email": "contact@themadrascafes.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Family restaurant\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 11,
    "name": "House of Tandoor",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: House of Tandoor (Family restaurant)\n★ Rating: ⭐ 4.6 (346 reviews)\n🏢 Address: Guru Brindhavan Garden, Vanagaram-Ambattur Rd, Adayalampattu, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=House%20of%20Tandoor&query_place_id=ChIJizLrGgBhUjoRahc-AapS51M\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "Guru Brindhavan Garden, Vanagaram-Ambattur Rd, Adayalampattu, Tamil Nadu",
    "budgetLakhs": 40,
    "source": "Google",
    "priority": "HOT",
    "phone": "9884600365",
    "email": "contact@houseoftandoor.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Family restaurant\",\"Adayalampattu\",\"Top Rated\"]"
  },
  {
    "serialNo": 12,
    "name": "SON'S Restaurant",
    "projectType": "Fine Dining & Hospitality Interior",
    "projectDescription": "📍 Google Maps Listing: SON'S Restaurant (Fine dining restaurant)\n★ Rating: ⭐ 4.1 (930 reviews)\n🏢 Address: No 21, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=SON%27S%20Restaurant&query_place_id=ChIJ20xB4NxhUjoRtax2mu6Tp-k\n💡 Project: Fine Dining & Hospitality Interior",
    "location": "No 21, Chennai, Tamil Nadu",
    "budgetLakhs": 45,
    "source": "Google",
    "priority": "WARM",
    "phone": "7358290985",
    "email": "contact@sonsrestaurant.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Fine dining restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 13,
    "name": "Swarnamukhii Cloud Kitchen",
    "projectType": "Commercial Cloud Kitchen Fitout",
    "projectDescription": "📍 Google Maps Listing: Swarnamukhii Cloud Kitchen (Restaurant)\n★ Rating: ⭐ 4.5 (76 reviews)\n🏢 Address: No14, Velan Nagar 9th St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Swarnamukhii%20Cloud%20Kitchen&query_place_id=ChIJZVqOcL1hUjoRuhRjkoGXVYE\n💡 Project: Commercial Cloud Kitchen Fitout",
    "location": "No14, Velan Nagar 9th St, Chennai, Tamil Nadu",
    "budgetLakhs": 25,
    "source": "Google",
    "priority": "HOT",
    "phone": "9566111646",
    "email": "contact@swarnamukhiiclo.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Restaurant\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 14,
    "name": "Tummie Filler's Restaurant",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Tummie Filler's Restaurant (Family restaurant)\n★ Rating: ⭐ 4.5 (42 reviews)\n🏢 Address: 3536+MCG, Chokkalingam Naicker 5th St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Tummie%20Filler%27s%20Restaurant&query_place_id=ChIJzbUb1v5hUjoRvIhCgLJE6xA\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "3536+MCG, Chokkalingam Naicker 5th St, Chennai, Tamil Nadu",
    "budgetLakhs": 30,
    "source": "Google",
    "priority": "HOT",
    "phone": "8148018613",
    "email": "contact@tummiefillersre.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Family restaurant\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 15,
    "name": "FAMILY RESTAURANT",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: FAMILY RESTAURANT (Family restaurant)\n★ Rating: ⭐ 5 (1 reviews)\n🏢 Address: Chennai, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=FAMILY%20RESTAURANT&query_place_id=ChIJFek8AnJhUjoRotAFtu5L5o4\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "Chennai, Chennai, Tamil Nadu",
    "budgetLakhs": 25,
    "source": "Google",
    "priority": "HOT",
    "phone": "8459946120",
    "email": "contact@familyrestauran.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Family restaurant\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 16,
    "name": "Resto Corner",
    "projectType": "Cafe & Commercial Interior",
    "projectDescription": "📍 Google Maps Listing: Resto Corner (Cafe)\n★ Rating: ⭐ 5 (10 reviews)\n🏢 Address: Plot No : 14, Abirami Nagar 4th St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Resto%20Corner&query_place_id=ChIJzfa_6BxhUjoRGfNyiXCEfMA\n💡 Project: Cafe & Commercial Interior",
    "location": "Plot No : 14, Abirami Nagar 4th St, Chennai, Tamil Nadu",
    "budgetLakhs": 22,
    "source": "Google",
    "priority": "HOT",
    "phone": "9962212724",
    "email": "contact@restocorner.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Cafe\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 17,
    "name": "Toast And Talk",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Toast And Talk (Restaurant)\n★ Rating: ⭐ 4.7 (3 reviews)\n🏢 Address: The Schram Academy 2, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Toast%20And%20Talk&query_place_id=ChIJgbNhAD9hUjoR9N-ZsskJ8T4\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "The Schram Academy 2, Chennai, Tamil Nadu",
    "budgetLakhs": 26,
    "source": "Google",
    "priority": "HOT",
    "phone": "8122907708",
    "email": "contact@toastandtalk.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Restaurant\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 18,
    "name": "MADURAVOYAL PANDIAN MESS",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: MADURAVOYAL PANDIAN MESS (Seafood restaurant)\n★ Rating: ⭐ 4.8 (1444 reviews)\n🏢 Address: 132, Alapakkam Main Rd, opp. meenakshi school, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=MADURAVOYAL%20PANDIAN%20MESS&query_place_id=ChIJuRDRe9lhUjoRVS4bxGPiXuc\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "132, Alapakkam Main Rd, opp. meenakshi school, Chennai, Tamil Nadu",
    "budgetLakhs": 38,
    "source": "Google",
    "priority": "HOT",
    "phone": "9962566625",
    "email": "contact@maduravoyalpand.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Seafood restaurant\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 19,
    "name": "Arabian Home Food",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Arabian Home Food (Arab restaurant)\n★ Rating: ⭐ 4.3 (40 reviews)\n🏢 Address: 123, Mettukuppam Rd, near EB Office, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Arabian%20Home%20Food&query_place_id=ChIJcxswhAZhUjoRxGPTpuvDLuU\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "123, Mettukuppam Rd, near EB Office, Chennai, Tamil Nadu",
    "budgetLakhs": 28,
    "source": "Google",
    "priority": "WARM",
    "phone": "9884880570",
    "email": "contact@arabianhomefood.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Arab restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 20,
    "name": "Kadher Bhai Biryani Maduravoyal (K2B)",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Kadher Bhai Biryani Maduravoyal (K2B) (Biryani restaurant)\n★ Rating: ⭐ 4 (1387 reviews)\n🏢 Address: 3578+RRM, 4, Sannathi St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Kadher%20Bhai%20Biryani%20Maduravoyal%20(K2B)&query_place_id=ChIJ7VW4MMJhUjoR030-fphoxWU\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "3578+RRM, 4, Sannathi St, Chennai, Tamil Nadu",
    "budgetLakhs": 35,
    "source": "Google",
    "priority": "WARM",
    "phone": "7397377725",
    "email": "contact@kadherbhaibirya.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Biryani restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 21,
    "name": "BIRIYANI CHOWK",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: BIRIYANI CHOWK (Family restaurant)\n★ Rating: ⭐ 4.2 (29 reviews)\n🏢 Address: Maduravoyal #15, MCK Layout, Bypass, Service Rd, Adayalampattu, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=BIRIYANI%20CHOWK&query_place_id=ChIJO0Eg8MBhUjoRJJqJNoNgKGk\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "Maduravoyal #15, MCK Layout, Bypass, Service Rd, Adayalampattu, Chennai, Tamil Nadu",
    "budgetLakhs": 30,
    "source": "Google",
    "priority": "WARM",
    "phone": "8438184010",
    "email": "contact@biriyanichowk.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Family restaurant\",\"Adayalampattu, Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 22,
    "name": "Crown Brick Construction",
    "projectType": "Turnkey Architecture & Construction",
    "projectDescription": "📍 Google Maps Listing: Crown Brick Construction (Construction company)\n★ Rating: ⭐ 4 (5 reviews)\n🏢 Address: 171, Poonamallee High Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Crown%20Brick%20Construction&query_place_id=ChIJwxdv7l5hUjoRwSaMeueaiLs\n💡 Project: Turnkey Architecture & Construction",
    "location": "171, Poonamallee High Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 50,
    "source": "Google",
    "priority": "WARM",
    "phone": "9600426219",
    "email": "contact@crownbrickconst.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 23,
    "name": "RIVER SAND M SAND P SAND AVAILABLE",
    "projectType": "Industrial Infrastructure & Supply",
    "projectDescription": "📍 Google Maps Listing: RIVER SAND M SAND P SAND AVAILABLE (Construction material wholesaler)\n★ Rating: ⭐ 5 (38 reviews)\n🏢 Address: Muthumari Amman Kovil street New subramanian Nagar, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=RIVER%20SAND%20M%20SAND%20P%20SAND%20AVAILABLE&query_place_id=ChIJNfMH_DxhUjoR93KPadF6PtU\n💡 Project: Industrial Infrastructure & Supply",
    "location": "Muthumari Amman Kovil street New subramanian Nagar, Chennai, Tamil Nadu",
    "budgetLakhs": 40,
    "source": "Google",
    "priority": "HOT",
    "phone": "9941966474",
    "email": "contact@riversandmsandp.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Construction material wholesaler\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 24,
    "name": "3Star Infra Engineering.",
    "projectType": "Industrial Infrastructure & Heavy Engineering",
    "projectDescription": "📍 Google Maps Listing: 3Star Infra Engineering. (Construction machine rental service)\n★ Rating: ⭐ 5 (4 reviews)\n🏢 Address: Chennai, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=3Star%20Infra%20Engineering.&query_place_id=ChIJjzfOw01hUjoRXWMjB4wYhng\n💡 Project: Industrial Infrastructure & Heavy Engineering",
    "location": "Chennai, Chennai, Tamil Nadu",
    "budgetLakhs": 60,
    "source": "Google",
    "priority": "HOT",
    "phone": "7448633339",
    "email": "contact@3starinfraengin.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Construction machine rental service\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 25,
    "name": "Salem RR Biryani - Maduravoyal Branch",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Salem RR Biryani - Maduravoyal Branch (Biryani restaurant)\n★ Rating: ⭐ 3.3 (2324 reviews)\n🏢 Address: Post Office stopping, Mumbai Hwy, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Salem%20RR%20Biryani%20-%20Maduravoyal%20Branch&query_place_id=ChIJvWh76nZhUjoRnf4eZ0Pt1LQ\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "Post Office stopping, Mumbai Hwy, Chennai, Tamil Nadu",
    "budgetLakhs": 45,
    "source": "Google",
    "priority": "WARM",
    "phone": "4429492000",
    "email": "contact@salemrrbiryanim.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Biryani restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 26,
    "name": "2 Idly 1 Vadai Restaurant",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: 2 Idly 1 Vadai Restaurant (South Indian restaurant)\n★ Rating: ⭐ 4 (1015 reviews)\n🏢 Address: 3528+GG9, Alapakkam Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=2%20Idly%201%20Vadai%20Restaurant&query_place_id=ChIJHUxSftlhUjoRVYLMzPXfxmw\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "3528+GG9, Alapakkam Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 30,
    "source": "Google",
    "priority": "WARM",
    "phone": "7401654053",
    "email": "contact@2idly1vadairest.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"South Indian restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 27,
    "name": "Hotel Pandian",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Hotel Pandian (South Indian restaurant)\n★ Rating: ⭐ 3.7 (2793 reviews)\n🏢 Address: No1/10 Poonamallee High Road, Ganapathy Nagar, Maduravoyal, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Hotel%20Pandian&query_place_id=ChIJEaJS_3FhUjoRtX0_p_Dv0b4\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "No1/10 Poonamallee High Road, Ganapathy Nagar, Maduravoyal, Chennai, Tamil Nadu",
    "budgetLakhs": 35,
    "source": "Google",
    "priority": "WARM",
    "phone": "9176558648",
    "email": "contact@hotelpandian.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"South Indian restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 28,
    "name": "Sri Balavignesh Bhavan",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Sri Balavignesh Bhavan (South Indian restaurant)\n★ Rating: ⭐ 3.8 (522 reviews)\n🏢 Address: Kanchipuram - Chennai Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Sri%20Balavignesh%20Bhavan&query_place_id=ChIJH3llAHJhUjoRqeeUAqMODG4\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "Kanchipuram - Chennai Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 28,
    "source": "Google",
    "priority": "WARM",
    "phone": "4423860491",
    "email": "contact@sribalavigneshb.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"South Indian restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 29,
    "name": "Hotel Shenbagaa Bhavan",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Hotel Shenbagaa Bhavan (Vegan restaurant)\n★ Rating: ⭐ 3.9 (277 reviews)\n🏢 Address: 340, Poonamallee High Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Hotel%20Shenbagaa%20Bhavan&query_place_id=ChIJMTNBAENhUjoR6jAc8TuNKCo\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "340, Poonamallee High Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 32,
    "source": "Google",
    "priority": "HOT",
    "phone": "8939471378",
    "email": "contact@hotelshenbagaab.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Vegan restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 30,
    "name": "New Hyderabad Biriyani",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: New Hyderabad Biriyani (Hyderabadi restaurant)\n★ Rating: ⭐ 3.7 (61 reviews)\n🏢 Address: No.1, 98, Poonamallee High Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=New%20Hyderabad%20Biriyani&query_place_id=ChIJISLrLqthUjoRN5bNTyXtLzY\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "No.1, 98, Poonamallee High Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 25,
    "source": "Google",
    "priority": "WARM",
    "phone": "4424761776",
    "email": "contact@newhyderabadbir.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Hyderabadi restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 31,
    "name": "Bismillah Biriyani Stall and tiffen centre",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Bismillah Biriyani Stall and tiffen centre (Tiffin center)\n★ Rating: ⭐ 5 (2 reviews)\n🏢 Address: Kkr ent hospital, 2nd Main Rd, opposite mmda, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Bismillah%20Biriyani%20Stall%20and%20tiffen%20centre&query_place_id=ChIJDRVTJbhhUjoRB2CLuXKPxdk\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "Kkr ent hospital, 2nd Main Rd, opposite mmda, Chennai, Tamil Nadu",
    "budgetLakhs": 20,
    "source": "Google",
    "priority": "HOT",
    "phone": "9342045120",
    "email": "contact@bismillahbiriya.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Tiffin center\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 32,
    "name": "Naadan thattu",
    "projectType": "Commercial Dining & Hospitality Fitout",
    "projectDescription": "📍 Google Maps Listing: Naadan thattu (Kerala restaurant)\n★ Rating: ⭐ 3 (2 reviews)\n🏢 Address: No 48 a, 5th St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Naadan%20thattu&query_place_id=ChIJbdunz9xhUjoR3WrqF5yfVJs\n💡 Project: Commercial Dining & Hospitality Fitout",
    "location": "No 48 a, 5th St, Chennai, Tamil Nadu",
    "budgetLakhs": 18,
    "source": "Google",
    "priority": "COLD",
    "phone": "8848991423",
    "email": "contact@naadanthattu.in",
    "winProbability": 30,
    "tags": "[\"Fresh Lead\",\"Kerala restaurant\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 33,
    "name": "Roopa Rekha bakery",
    "projectType": "Retail Bakery & Cafe Design",
    "projectDescription": "📍 Google Maps Listing: Roopa Rekha bakery (Bakery)\n★ Rating: ⭐ 4 (25 reviews)\n🏢 Address: 13, Shridevikuppam Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Roopa%20Rekha%20bakery&query_place_id=ChIJO0YttTBhUjoRDfaXWXvXQf8\n💡 Project: Retail Bakery & Cafe Design",
    "location": "13, Shridevikuppam Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 22,
    "source": "Google",
    "priority": "WARM",
    "phone": "9962900186",
    "email": "contact@rooparekhabaker.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Bakery\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 34,
    "name": "Haia interiors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Haia interiors (Interior designer)\n★ Rating: ⭐ 4.9 (99 reviews)\n🏢 Address: 3524+2HM, Vanagaram, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Haia%20interiors&query_place_id=ChIJHVpHi4VhUjoRZHHDYK6GwLM\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "3524+2HM, Vanagaram, Tamil Nadu",
    "budgetLakhs": 27,
    "source": "Google",
    "priority": "HOT",
    "phone": "9790766388",
    "email": "contact@haiainteriors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Vanagaram\",\"Top Rated\"]"
  },
  {
    "serialNo": 35,
    "name": "Agaram interior",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Agaram interior (Interior designer)\n★ Rating: ⭐ 5 (8 reviews)\n🏢 Address: Mettukuppam Rd, Vanagaram, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Agaram%20interior&query_place_id=ChIJs2CjXwBhUjoRkxvAoYwfV0M\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "Mettukuppam Rd, Vanagaram, Tamil Nadu",
    "budgetLakhs": 33,
    "source": "Google",
    "priority": "HOT",
    "phone": "9840200713",
    "email": "contact@agaraminterior.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Vanagaram\",\"Top Rated\"]"
  },
  {
    "serialNo": 36,
    "name": "MAYA INTERIORS",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: MAYA INTERIORS (Interior designer)\n★ Rating: ⭐ 4.9 (68 reviews)\n🏢 Address: 3 chellammal Nagar, Mettu Rd, Thundalam, Thiruverkadu, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=MAYA%20INTERIORS&query_place_id=ChIJh2coR-BdUjoRsWbjq7INUiQ\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "3 chellammal Nagar, Mettu Rd, Thundalam, Thiruverkadu, Tamil Nadu",
    "budgetLakhs": 33,
    "source": "Google",
    "priority": "HOT",
    "phone": "9840808883",
    "email": "contact@mayainteriors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Thundalam, Thiruverkadu\",\"Top Rated\"]"
  },
  {
    "serialNo": 37,
    "name": "DESIGN YOUR HOME INTERIOR",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: DESIGN YOUR HOME INTERIOR (Interior designer)\n★ Rating: ⭐ 5 (2 reviews)\n🏢 Address: 320/12, varasakthi, 95, Vinayagar Kovil St, near veterinary hospital and EB office, Vanagaram, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=DESIGN%20YOUR%20HOME%20INTERIOR&query_place_id=ChIJJWHSA7FnUjoRwiO51f_QQFA\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "320/12, varasakthi, 95, Vinayagar Kovil St, near veterinary hospital and EB office, Vanagaram, Tamil Nadu",
    "budgetLakhs": 44,
    "source": "Google",
    "priority": "HOT",
    "phone": "9092024502",
    "email": "contact@designyourhomei.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Vanagaram\",\"Top Rated\"]"
  },
  {
    "serialNo": 38,
    "name": "Ｓｒｅｅ Ｓａｉ Ｉｎｔｅｒｉｏｒｓ",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Ｓｒｅｅ Ｓａｉ Ｉｎｔｅｒｉｏｒｓ (Interior designer)\n★ Rating: ⭐ 3.4 (9 reviews)\n🏢 Address: Vanagaram, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=%EF%BC%B3%EF%BD%92%EF%BD%85%EF%BD%85%20%EF%BC%B3%EF%BD%81%EF%BD%89%20%EF%BC%A9%EF%BD%8E%EF%BD%94%EF%BD%85%EF%BD%92%EF%BD%89%EF%BD%8F%EF%BD%92%EF%BD%93&query_place_id=ChIJ6c7W_zNhUjoRq0171ZdOVk0\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "Vanagaram, Tamil Nadu",
    "budgetLakhs": 55,
    "source": "Google",
    "priority": "WARM",
    "phone": "7550194215",
    "email": "contact@.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Vanagaram\",\"Verified\"]"
  },
  {
    "serialNo": 39,
    "name": "MRS interior decorator",
    "projectType": "Custom Woodwork & Commercial Interiors",
    "projectDescription": "📍 Google Maps Listing: MRS interior decorator (Woodworker)\n★ Rating: ⭐ 5 (17 reviews)\n🏢 Address: 345W+6M6 Cluster_ambattur 17, 12/27, Noombal Main Rd, Thiruverkadu, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=MRS%20interior%20decorator&query_place_id=ChIJGdXRY0JdUjoRZ5Z2d-wm3D0\n💡 Project: Custom Woodwork & Commercial Interiors",
    "location": "345W+6M6 Cluster_ambattur 17, 12/27, Noombal Main Rd, Thiruverkadu, Tamil Nadu",
    "budgetLakhs": 59,
    "source": "Google",
    "priority": "HOT",
    "phone": "9790755063",
    "email": "contact@mrsinteriordeco.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Woodworker\",\"Thiruverkadu\",\"Top Rated\"]"
  },
  {
    "serialNo": 40,
    "name": "Aganam Interiors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Aganam Interiors (Interior designer)\n★ Rating: ⭐ 4.7 (6 reviews)\n🏢 Address: 131, Poonamallee High Rd, Thiruverkadu, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Aganam%20Interiors&query_place_id=ChIJ5UxnYSphUjoRKEdvDIjHEVU\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "131, Poonamallee High Rd, Thiruverkadu, Tamil Nadu",
    "budgetLakhs": 38,
    "source": "Google",
    "priority": "HOT",
    "phone": "9962221632",
    "email": "contact@aganaminteriors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Thiruverkadu\",\"Top Rated\"]"
  },
  {
    "serialNo": 41,
    "name": "Saran Decors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Saran Decors (Interior designer)\n★ Rating: ⭐ 5 (3 reviews)\n🏢 Address: 28/2A, Poonamallee High Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Saran%20Decors&query_place_id=ChIJv6S_TkRhUjoR5jqClGN4-2U\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "28/2A, Poonamallee High Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 45,
    "source": "Google",
    "priority": "HOT",
    "phone": "9841792224",
    "email": "contact@sarandecors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 42,
    "name": "RK TEMPO DESIGNER",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: RK TEMPO DESIGNER (Interior designer)\n★ Rating: ⭐ 5 (8 reviews)\n🏢 Address: 11 Masilamani, Vembuli Naicker St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=RK%20TEMPO%20DESIGNER&query_place_id=ChIJt6IWagBhUjoRvYAnYkMgRlw\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "11 Masilamani, Vembuli Naicker St, Chennai, Tamil Nadu",
    "budgetLakhs": 36,
    "source": "Google",
    "priority": "HOT",
    "phone": "9150779690",
    "email": "contact@rktempodesigner.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 43,
    "name": "Venus Interiors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Venus Interiors (Interior designer)\n★ Rating: ⭐ 5 (4 reviews)\n🏢 Address: Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Venus%20Interiors&query_place_id=ChIJaf7yXXlhUjoRi6-M3dRfRNU\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "Chennai, Tamil Nadu",
    "budgetLakhs": 49,
    "source": "Google",
    "priority": "HOT",
    "phone": "9841655848",
    "email": "contact@venusinteriors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 44,
    "name": "NESH DESIGN STUDIO",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: NESH DESIGN STUDIO (Interior architect office)\n★ Rating: ⭐ 4.8 (10 reviews)\n🏢 Address: 1/146, Poonamallee High Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=NESH%20DESIGN%20STUDIO&query_place_id=ChIJz2pMbFJhUjoRTlN9u2XwWUU\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "1/146, Poonamallee High Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 56,
    "source": "Google",
    "priority": "HOT",
    "phone": "8531934330",
    "email": "contact@neshdesignstudi.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior architect office\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 45,
    "name": "Aerocon R N Associates",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Aerocon R N Associates (Interior designer)\n★ Rating: ⭐ 4.8 (10 reviews)\n🏢 Address: Indira Nagar shivaboothamedu, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Aerocon%20R%20N%20Associates&query_place_id=ChIJ5VtxXNRhUjoRQQKk-wvup2Y\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "Indira Nagar shivaboothamedu, Chennai, Tamil Nadu",
    "budgetLakhs": 48,
    "source": "Google",
    "priority": "HOT",
    "phone": "9566295602",
    "email": "contact@aeroconrnassoci.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 46,
    "name": "I Five Interiors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: I Five Interiors (Interior designer)\n★ Rating: ⭐ 5 (11 reviews)\n🏢 Address: RK Towers, Chokkanathar St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=I%20Five%20Interiors&query_place_id=ChIJDRKh-FZdUjoRoanhULW0deE\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "RK Towers, Chokkanathar St, Chennai, Tamil Nadu",
    "budgetLakhs": 42,
    "source": "Google",
    "priority": "HOT",
    "phone": "8438532235",
    "email": "contact@ifiveinteriors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 47,
    "name": "Classic Home Interiors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Classic Home Interiors (Interior designer)\n★ Rating: ⭐ 4.6 (52 reviews)\n🏢 Address: Mettukuppam Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Classic%20Home%20Interiors&query_place_id=ChIJ4QrDE0dhUjoRWr-ArbTbdDk\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "Mettukuppam Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 42,
    "source": "Google",
    "priority": "HOT",
    "phone": "8608054350",
    "email": "contact@classichomeinte.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 48,
    "name": "Artistry Interiors & Netlon",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Artistry Interiors & Netlon (Interior designer)\n★ Rating: ⭐ 4.8 (30 reviews)\n🏢 Address: No3, Chandran Street, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Artistry%20Interiors%20%26%20Netlon&query_place_id=ChIJ59g8dsxhUjoRDHHbqs6XbNc\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "No3, Chandran Street, Chennai, Tamil Nadu",
    "budgetLakhs": 53,
    "source": "Google",
    "priority": "HOT",
    "phone": "9677177726",
    "email": "contact@artistryinterio.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 49,
    "name": "NEST'S INTERIORS",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: NEST'S INTERIORS (Interior designer)\n★ Rating: ⭐ 4.9 (12 reviews)\n🏢 Address: 11 old 1/53 VINAYAGAR KOVIL STREET, 2nd St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=NEST'S%20INTERIORS&query_place_id=ChIJo1xYIJVmUjoRlRQwdoHKSEM\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "11 old 1/53 VINAYAGAR KOVIL STREET, 2nd St, Chennai, Tamil Nadu",
    "budgetLakhs": 41,
    "source": "Google",
    "priority": "HOT",
    "phone": "8778113263",
    "email": "contact@nestsinteriors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 50,
    "name": "Eva Consociate The Interior Lab",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Eva Consociate The Interior Lab (Interior designer)\n★ Rating: ⭐ 4.8 (28 reviews)\n🏢 Address: Hariom Complex, 135-A, Poonamallee High Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Eva%20Consociate%20The%20Interior%20Lab&query_place_id=ChIJa2CeGsRhUjoRJzv4TTiJW3g\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "Hariom Complex, 135-A, Poonamallee High Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 44,
    "source": "Google",
    "priority": "HOT",
    "phone": "8778390270",
    "email": "contact@evaconsociateth.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 51,
    "name": "D2 INTERIORS",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: D2 INTERIORS (Interior Decorator)\n★ Rating: ⭐ 4.7 (19 reviews)\n🏢 Address: Old no 1/502 New no 1, 546, W Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=D2%20INTERIORS&query_place_id=ChIJZceKzKZhUjoRbiDii-Llsmg\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "Old no 1/502 New no 1, 546, W Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 54,
    "source": "Google",
    "priority": "HOT",
    "phone": "9092342255",
    "email": "contact@d2interiors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior Decorator\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 52,
    "name": "Greenspace Interior",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Greenspace Interior (Interior designer)\n★ Rating: ⭐ 4.5 (19 reviews)\n🏢 Address: 2nd floor, 1/11A, Balambigai Nagar 4th St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Greenspace%20Interior&query_place_id=ChIJSQg-Qr9nUjoRkY27rK164Jw\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "2nd floor, 1/11A, Balambigai Nagar 4th St, Chennai, Tamil Nadu",
    "budgetLakhs": 57,
    "source": "Google",
    "priority": "WARM",
    "phone": "9952869973",
    "email": "contact@greenspaceinter.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 53,
    "name": "L2K interiors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: L2K interiors (Interior Decorator)\n★ Rating: ⭐ 4.3 (19 reviews)\n🏢 Address: 2/169,mugalivakkam to madhanandhapuram, Main Rd, near Bharath petroleum, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=L2K%20interiors&query_place_id=ChIJNysCGK1hUjoRMW0HNwmh5O0\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "2/169,mugalivakkam to madhanandhapuram, Main Rd, near Bharath petroleum, Chennai, Tamil Nadu",
    "budgetLakhs": 28,
    "source": "Google",
    "priority": "WARM",
    "phone": "8939287874",
    "email": "contact@l2kinteriors.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Interior Decorator\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 54,
    "name": "S S design",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: S S design (Interior Decorator)\n★ Rating: ⭐ 5 (4 reviews)\n🏢 Address: No.288/2C, Mustaffa Street, Kandasamy Nagar Extn, Mettukuppam Rd, Vanagaram, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=S%20S%20design&query_place_id=ChIJtw-A8Y5hUjoRItl4UvC9afg\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "No.288/2C, Mustaffa Street, Kandasamy Nagar Extn, Mettukuppam Rd, Vanagaram, Tamil Nadu",
    "budgetLakhs": 27,
    "source": "Google",
    "priority": "HOT",
    "phone": "9941404046",
    "email": "contact@ssdesign.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior Decorator\",\"Vanagaram\",\"Top Rated\"]"
  },
  {
    "serialNo": 55,
    "name": "RSK Interiors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: RSK Interiors (Interior designer)\n★ Rating: ⭐ 5 (1 reviews)\n🏢 Address: 72, Balaraman St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=RSK%20Interiors&query_place_id=ChIJcQ-tygRhUjoRfx-EfMHdl9I\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "72, Balaraman St, Chennai, Tamil Nadu",
    "budgetLakhs": 40,
    "source": "Google",
    "priority": "HOT",
    "phone": "9940194731",
    "email": "contact@rskinteriors.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 56,
    "name": "SS INTERIOR AND MODULAR",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: SS INTERIOR AND MODULAR (Manufacturer)\n★ Rating: ⭐ 5 (1 reviews)\n🏢 Address: Plot no 2, Thiru Vi Ka St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=SS%20INTERIOR%20AND%20MODULAR&query_place_id=ChIJP0dUYgBhUjoRB0V56R9r8e4\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "Plot no 2, Thiru Vi Ka St, Chennai, Tamil Nadu",
    "budgetLakhs": 55,
    "source": "Google",
    "priority": "HOT",
    "phone": "9962799022",
    "email": "contact@ssinteriorandmo.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Manufacturer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 57,
    "name": "Aadithya Agencies",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Aadithya Agencies (Interior Decorator)\n★ Rating: ⭐ 5 (10 reviews)\n🏢 Address: CSR towers, 5th Cross St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Aadithya%20Agencies&query_place_id=ChIJe5wqLgBhUjoRt92QAnvdL8M\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "CSR towers, 5th Cross St, Chennai, Tamil Nadu",
    "budgetLakhs": 47,
    "source": "Google",
    "priority": "HOT",
    "phone": "9840577538",
    "email": "contact@aadithyaagencie.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior Decorator\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 58,
    "name": "Home interior chennai",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Home interior chennai (Apartment complex)\n★ Rating: ⭐ 5 (2 reviews)\n🏢 Address: 2/6, Kalaignar Street, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Home%20interior%20chennai&query_place_id=ChIJWSI2ku9hUjoRSkKtPdCjnDA\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "2/6, Kalaignar Street, Chennai, Tamil Nadu",
    "budgetLakhs": 44,
    "source": "Google",
    "priority": "HOT",
    "phone": "9380937048",
    "email": "contact@homeinteriorche.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Apartment complex\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 59,
    "name": "SRIKO Associates",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: SRIKO Associates (Interior designer)\n★ Rating: ⭐ 4.7 (15 reviews)\n🏢 Address: No 110, Mugalivakkam Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=SRIKO%20Associates&query_place_id=ChIJDf_tb-ZgUjoRgy7HWKxvphM\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "No 110, Mugalivakkam Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 34,
    "source": "Google",
    "priority": "HOT",
    "phone": "9176009669",
    "email": "contact@srikoassociates.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 60,
    "name": "Santhanu Interiors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Santhanu Interiors (Interior designer)\n★ Rating: ⭐ 4.8 (10 reviews)\n🏢 Address: No.118, Poothapedu Main Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Santhanu%20Interiors&query_place_id=ChIJA6VuyNhgUjoRsPi0BYTGvN0\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "No.118, Poothapedu Main Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 43,
    "source": "Google",
    "priority": "HOT",
    "phone": "9444109972",
    "email": "contact@santhanuinterio.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 61,
    "name": "Design i.O",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Design i.O (Interior designer)\n★ Rating: ⭐ 5 (2 reviews)\n🏢 Address: 14,Rajiv nagar, 1st St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Design%20i.O&query_place_id=ChIJuSZl-hBhUjoRmCg-GylpGk8\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "14,Rajiv nagar, 1st St, Chennai, Tamil Nadu",
    "budgetLakhs": 32,
    "source": "Google",
    "priority": "HOT",
    "phone": "7397296311",
    "email": "contact@designio.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 62,
    "name": "Ksj Interior",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Ksj Interior (Interior designer)\n★ Rating: ⭐ 4.8 (10 reviews)\n🏢 Address: 25, 7th Lane, 6th Cross St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Ksj%20Interior&query_place_id=ChIJm_D-z2lhUjoRP8mULyBpDb8\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "25, 7th Lane, 6th Cross St, Chennai, Tamil Nadu",
    "budgetLakhs": 58,
    "source": "Google",
    "priority": "HOT",
    "phone": "9710588175",
    "email": "contact@ksjinterior.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 63,
    "name": "R R CNC Wood Works",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: R R CNC Wood Works (Interior designer)\n★ Rating: ⭐ 4.4 (75 reviews)\n🏢 Address: 10, 1st St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=R%20R%20CNC%20Wood%20Works&query_place_id=ChIJaZQdLDZhUjoRpw5cgou99pQ\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "10, 1st St, Chennai, Tamil Nadu",
    "budgetLakhs": 57,
    "source": "Google",
    "priority": "HOT",
    "phone": "9884444682",
    "email": "contact@rrcncwoodworks.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 64,
    "name": "RAGAVENDRA INTERIOR",
    "projectType": "Interior Materials & Supply",
    "projectDescription": "📍 Google Maps Listing: RAGAVENDRA INTERIOR (Plywood supplier)\n★ Rating: ⭐ 5 (6 reviews)\n🏢 Address: 1, Balaraman St, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=RAGAVENDRA%20INTERIOR&query_place_id=ChIJL9UXx7FhUjoR2m1rWSXNwCA\n💡 Project: Interior Materials & Supply",
    "location": "1, Balaraman St, Chennai, Tamil Nadu",
    "budgetLakhs": 49,
    "source": "Google",
    "priority": "HOT",
    "phone": "8148048006",
    "email": "contact@ragavendrainter.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Plywood supplier\",\"Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 65,
    "name": "Pixel Space",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Pixel Space (Interior designer)\n★ Rating: ⭐ 3 (2 reviews)\n🏢 Address: 330G, Poonamallee High Rd, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Pixel%20Space&query_place_id=ChIJDVstqENhUjoRPPJIRkSReeU\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "330G, Poonamallee High Rd, Chennai, Tamil Nadu",
    "budgetLakhs": 49,
    "source": "Google",
    "priority": "WARM",
    "phone": "9840785592",
    "email": "contact@pixelspace.in",
    "winProbability": 50,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Chennai\",\"Verified\"]"
  },
  {
    "serialNo": 66,
    "name": "SR Interior",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: SR Interior (Interior designer)\n★ Rating: ⭐ 5 (4 reviews)\n🏢 Address: 30, Cauvery Nagar Main Rd, Thiruverkadu, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=SR%20Interior&query_place_id=ChIJy12YmCZhUjoRmVfQqIid0ag\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "30, Cauvery Nagar Main Rd, Thiruverkadu, Tamil Nadu",
    "budgetLakhs": 35,
    "source": "Google",
    "priority": "HOT",
    "phone": "9941484565",
    "email": "contact@srinterior.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Thiruverkadu\",\"Top Rated\"]"
  },
  {
    "serialNo": 67,
    "name": "LEMON Transforming Spaces",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: LEMON Transforming Spaces (Interior designer)\n★ Rating: ⭐ 4.7 (70 reviews)\n🏢 Address: 33, Rajiv Gandhi St, Ayyappanthangal, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=LEMON%20Transforming%20Spaces&query_place_id=ChIJY3nZ03VhUjoRmbNrYOgAeTk\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "33, Rajiv Gandhi St, Ayyappanthangal, Tamil Nadu",
    "budgetLakhs": 54,
    "source": "Google",
    "priority": "HOT",
    "phone": "9499960791",
    "email": "contact@lemontransformi.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior designer\",\"Ayyappanthangal\",\"Top Rated\"]"
  },
  {
    "serialNo": 68,
    "name": "Urban False Ceiling Works - Partition & Painting Contractors",
    "projectType": "Luxury Residential & Commercial Interior Design",
    "projectDescription": "📍 Google Maps Listing: Urban False Ceiling Works - Partition & Painting Contractors (Interior Decorator)\n★ Rating: ⭐ 5 (50 reviews)\n🏢 Address: 29/2, Siva Ramiyar St, Adayalampattu, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=Urban%20False%20Ceiling%20Works%20-%20Partition%20%26%20Painting%20Contractors&query_place_id=ChIJX0IebGJhUjoRSwK8tZQ09Y0\n💡 Project: Luxury Residential & Commercial Interior Design",
    "location": "29/2, Siva Ramiyar St, Adayalampattu, Chennai, Tamil Nadu",
    "budgetLakhs": 54,
    "source": "Google",
    "priority": "HOT",
    "phone": "8778727722",
    "email": "contact@urbanfalseceili.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Interior Decorator\",\"Adayalampattu, Chennai\",\"Top Rated\"]"
  },
  {
    "serialNo": 69,
    "name": "MJ ENTERPRISES",
    "projectType": "Turnkey Interior & Construction",
    "projectDescription": "📍 Google Maps Listing: MJ ENTERPRISES (Construction company)\n★ Rating: ⭐ 5 (52 reviews)\n🏢 Address: No.66,4thcross st, chokkalingam nagar, Chennai, Tamil Nadu\n🌐 Maps Link: https://www.google.com/maps/search/?api=1&query=MJ%20ENTERPRISES&query_place_id=ChIJB77fS01hUjoR5-37RE9tZpg\n💡 Project: Turnkey Interior & Construction",
    "location": "No.66,4thcross st, chokkalingam nagar, Chennai, Tamil Nadu",
    "budgetLakhs": 36,
    "source": "Google",
    "priority": "HOT",
    "phone": "8825504211",
    "email": "contact@mjenterprises.in",
    "winProbability": 75,
    "tags": "[\"Fresh Lead\",\"Construction company\",\"Chennai\",\"Top Rated\"]"
  }
];

async function main() {
  console.log('🚀 Seeding verified leads starting at DND-001...');

  const passwordHash = await bcrypt.hash('password123', 12);

  const nirmal = await prisma.user.upsert({
    where: { email: 'nirmalkumar00727@gmail.com' },
    update: { name: 'Nirmal kumar N', role: 'ADMIN', initials: 'N' },
    create: { email: 'nirmalkumar00727@gmail.com', password: passwordHash, name: 'Nirmal kumar N', role: 'ADMIN', initials: 'N' },
  });

  const gayathri = await prisma.user.upsert({
    where: { email: 'gayathrideva2007@gmail.com' },
    update: { name: 'Gayathri', role: 'PRINCIPAL', initials: 'G' },
    create: { email: 'gayathrideva2007@gmail.com', password: passwordHash, name: 'Gayathri', role: 'PRINCIPAL', initials: 'G' },
  });

  await prisma.activity.deleteMany({});
  await prisma.note.deleteMany({});
  await prisma.meeting.deleteMany({});
  await prisma.fileAsset.deleteMany({});
  await prisma.proposal.deleteMany({});
  await prisma.notification.deleteMany({});
  await prisma.lead.deleteMany({});

  try {
    await prisma.$executeRawUnsafe("SELECT setval(pg_get_serial_sequence('leads', 'serialNo'), 1, false);");
  } catch (e) {}

  const owners = [gayathri, nirmal];

  for (let i = 0; i < ALL_LEADS_DATA.length; i++) {
    const item = ALL_LEADS_DATA[i];
    const owner = owners[i % owners.length];
    const leadCode = "DND-" + String(item.serialNo).padStart(3, '0');

    await prisma.lead.create({
      data: {
        id: leadCode,
        serialNo: item.serialNo,
        name: item.name,
        projectType: item.projectType,
        projectDescription: item.projectDescription,
        location: item.location,
        budgetLakhs: item.budgetLakhs,
        source: item.source || 'Google',
        priority: item.priority as any,
        phone: item.phone,
        email: item.email,
        ownerId: owner.id,
        winProbability: item.winProbability,
        tags: item.tags,
        stage: 'NEW',
        stageChangedAt: new Date(),
      },
    });
  }

  console.log('✅ Seeded all ' + ALL_LEADS_DATA.length + ' leads successfully!');
}

main().catch(console.error).finally(() => prisma.$disconnect());
