import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

export const RAW_LEADS_DATA = [
  {
    name: 'JNOVE RESTAURANT',
    rating: 4.5,
    reviews: 2196,
    street: 'no 51',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 63844 43333',
    category: 'Indian restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=JNOVE%20RESTAURANT&query_place_id=ChIJSc798pNdUjoR1nJwO8rlM4U',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 2.5,
    projectType: 'Food Ordering Mobile App & QR Menu',
  },
  {
    name: 'Restaurant@Thoraipakkam',
    rating: 4.9,
    reviews: 190,
    street: '1/812,PILLAIYAR KOVIL STREET, THURAIPAKKAM, CHENNAI - 600097',
    city: 'Chennai, Thoraipakkam',
    state: 'Tamil Nadu',
    phone: '+91 90402 45678',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Restaurant%40Thoraipakkam&query_place_id=ChIJvc01SExdUjoRB8lXDmoXfaw',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.8,
    projectType: 'Online Ordering Website & Digital Menu',
  },
  {
    name: 'Kongu Style - Family Restaurant',
    rating: 5.0,
    reviews: 14,
    street: '41, East Coast Rd, inside Redwood Resorts',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Family restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Kongu%20Style%20-%20Family%20Restaurant&query_place_id=ChIJr7d7_S5dUjoRPk8L9ChwtRE',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.6,
    projectType: 'Restaurant Branding & Portfolio Website',
  },
  {
    name: 'Kadarkarai Seafood restaurant',
    rating: 4.8,
    reviews: 208,
    street: 'MGR Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 84382 86805',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Kadarkarai%20Seafood%20restaurant&query_place_id=ChIJ25LJqhZdUjoRV8HKoB7vb_8',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.5,
    projectType: 'Table Reservation & Online Menu App',
  },
  {
    name: 'Habbat Global Cuisine Restaurant',
    rating: 4.1,
    reviews: 3783,
    street: 'OMR Food Street',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 89258 33736',
    category: 'Turkish restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Habbat%20Global%20Cuisine%20Restaurant&query_place_id=ChIJg1zxm6RdUjoRClv_kxVq2Wc',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 3.0,
    projectType: 'Cross-Platform Customer Loyalty & Ordering App',
  },
  {
    name: 'Bowl And Roll Theory',
    rating: 4.7,
    reviews: 211,
    street: 'H, SHRI HOMES, NO:3/452, Rajiv Gandhi Salai',
    city: 'Thoraipakkam',
    state: 'Tamil Nadu',
    phone: '+91 91768 33699',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Bowl%20And%20Roll%20Theory&query_place_id=ChIJoV3ih4RdUjoRgYEtWIQZ6Eo',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.2,
    projectType: 'Quick-Service Website & Digital Ordering',
  },
  {
    name: 'Nandavanam Veg Restaurant',
    rating: 4.0,
    reviews: 1539,
    street: 'Annai Parvathy street, 10A, Rajiv Gandhi Salai',
    city: 'Thoraipakkam',
    state: 'Tamil Nadu',
    phone: '+91 73587 71949',
    category: 'Vegetarian restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Nandavanam%20Veg%20Restaurant&query_place_id=ChIJGSxxivJdUjoR0BbCFr12JPo',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 2.0,
    projectType: 'Online Delivery Portal & POS Integration',
  },
  {
    name: 'The Mayflower',
    rating: 4.1,
    reviews: 1603,
    street: '28, MGR Salai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 80981 89000',
    category: 'Continental restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=The%20Mayflower&query_place_id=ChIJh4-K6mldUjoR8Gblv1nMCH4',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 2.2,
    projectType: 'Fine Dining Showcase Website & Reservation System',
  },
  {
    name: 'Spice And Dum Restaurant',
    rating: 4.2,
    reviews: 452,
    street: '9, MGR Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 98400 12345',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Spice%20And%20Dum%20Restaurant&query_place_id=ChIJhw-OBSpbUjoRZMdx3eh3PGQ',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 1.0,
    projectType: 'Biryani Special Menu & Direct Ordering Web App',
  },
  {
    name: 'SRI SARAN CONSTRUCTION AND RENOVATION',
    rating: 5.0,
    reviews: 11,
    street: '2/361',
    city: 'Thoraipakkam, Chennai',
    state: 'Tamil Nadu',
    phone: '+91 94440 98765',
    category: 'Interior construction contractor',
    url: 'https://www.google.com/maps/search/?api=1&query=SRI%20SARAN%20CONSTRUCTION%20AND%20RENOVATION&query_place_id=ChIJtwoY4wldUjoRGCLDg1kXh-o',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.9,
    projectType: 'Renovation Portfolio Website & Estimate Calculator',
  },
  {
    name: 'Neem tree Enterprise',
    rating: 4.0,
    reviews: 5,
    street: '2/554, 1st Main Rd Sandeep Ave',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Neem%20tree%20Enterprise&query_place_id=ChIJf2YbLwBdUjoRfZndwIkKqXI',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.5,
    projectType: 'Corporate Portfolio & Lead Capture Website',
  },
  {
    name: 'Idhayavarshini Construction',
    rating: 5.0,
    reviews: 1,
    street: '22, Ponniamman Koil 2nd St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 99520 99168',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Idhayavarshini%20Construction&query_place_id=ChIJubbWMABbUjoRIiPZtQMqU6k',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.75,
    projectType: 'Builder Showcase Website & Mobile Portfolio',
  },
  {
    name: 'Green construction & interior',
    rating: 5.0,
    reviews: 37,
    street: 'srinivas nagar, 1/623, 8th St',
    city: 'Thoraipakkam',
    state: 'Tamil Nadu',
    phone: '+91 97911 49521',
    category: 'Building consultant',
    url: 'https://www.google.com/maps/search/?api=1&query=Green%20construction%20%26%20interior&query_place_id=ChIJo9MouR5dUjoRii_-dl0KFhA',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.4,
    projectType: 'Sustainable Architecture Portfolio & Client Portal',
  },
  {
    name: 'P Square Constructions',
    rating: 5.0,
    reviews: 1,
    street: 'W66M+X56',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=P%20Square%20Constructions&query_place_id=ChIJxZGlQwBdUjoRrBUW8jhBFBQ',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.6,
    projectType: 'Contractor Website & Completed Projects Gallery',
  },
  {
    name: 'VLMAKS HOMES',
    rating: 5.0,
    reviews: 2,
    street: 'East Coast Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 98401 55667',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=VLMAKS%20HOMES&query_place_id=ChIJ9RTTAwBdUjoRPPL4Z9vg_v8',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.8,
    projectType: 'Luxury Homes Villa Portfolio Website',
  },
  {
    name: 'Selvan Construction',
    rating: 4.2,
    reviews: 8,
    street: 'W6x',
    city: 'Thoraipakkam, Kanchipuram',
    state: 'Tamil Nadu',
    phone: '+91 98408 28398',
    category: 'General contractor',
    url: 'https://www.google.com/maps/search/?api=1&query=Selvan%20Construction&query_place_id=ChIJX6itdL9dUjoRsOfs48R9XN4',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.65,
    projectType: 'Civil Contractor Portfolio & Services Web Page',
  },
  {
    name: 'AB Enterprises',
    rating: 5.0,
    reviews: 1,
    street: 'X63J+4X2, 3rd Main Rd',
    city: 'Thoraipakkam, Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=AB%20Enterprises&query_place_id=ChIJ2-3WeABdUjoRcZSxls9lH1g',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.5,
    projectType: 'Material & Construction Business Website',
  },
  {
    name: 'Anand Traders',
    rating: 4.7,
    reviews: 3,
    street: '5/344, Santhosh Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 98416 20019',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Anand%20Traders&query_place_id=ChIJ_b5ovBNdUjoRAAAAMKjbu0U',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.7,
    projectType: 'Building Materials Catalog & Inquiry App',
  },
  {
    name: 'Diamond house construction',
    rating: 4.5,
    reviews: 4,
    street: 'X66Q+7WX, Elim Nagar Manthopu 1st Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Diamond%20house%20construction&query_place_id=ChIJi2v4YwBdUjoRltW_AqhhK7I',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.6,
    projectType: 'Residential Construction Portfolio Website',
  },
  {
    name: 'VJ Construction and Developers',
    rating: 4.3,
    reviews: 6,
    street: '3/143, East Coast Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 98840 22334',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=VJ%20Construction%20and%20Developers&query_place_id=ChIJ8_7tEhddUjoRb-rmTEOXuvw',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 1.1,
    projectType: 'Real Estate Developer Landing Page & Lead Funnel',
  },
  {
    name: 'Green Stone',
    rating: 4.0,
    reviews: 4,
    street: '283, 1st Cross St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 99626 65566',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Green%20Stone&query_place_id=ChIJ6fOMtEZdUjoR-GzEwS14HVQ',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.7,
    projectType: 'Stone Craft & Construction Showcase Site',
  },
  {
    name: 'RR FOUNDATIONS',
    rating: 5.0,
    reviews: 2,
    street: '1st Cross St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 96770 79421',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=RR%20FOUNDATIONS&query_place_id=ChIJdaFnXatnUjoRDZIg6W5W0BY',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.85,
    projectType: 'Structural & Foundation Projects Portfolio',
  },
  {
    name: 'Aqsa properties and developers',
    rating: 5.0,
    reviews: 2,
    street: 'X744+7GP, 2nd Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Aqsa%20properties%20and%20developers&query_place_id=ChIJCUpmbABdUjoRuhZLZLHWFk0',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.65,
    projectType: 'Property Showcase Web App & Gallery',
  },
  {
    name: 'THIS Chennai',
    rating: 5.0,
    reviews: 2,
    street: '4/390, Ram gardens, Anna Salai Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 99400 80581',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=THIS%20Chennai&query_place_id=ChIJIamk399dUjoRaiJq2lrCuHk',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.8,
    projectType: 'Boutique Dining Portfolio Website',
  },
  {
    name: 'NIGHT EAT',
    rating: 4.0,
    reviews: 83,
    street: 'NO:3/164,1ST FLOOR, Perumbakkam Main Rd',
    city: 'Chennai, Medavakkam',
    state: 'Tamil Nadu',
    phone: '+91 88380 38315',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=NIGHT%20EAT&query_place_id=ChIJTWV_DQRdUjoRUDARderXl0g',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.2,
    projectType: 'Late-Night Food Delivery Web App & Mobile Portal',
  },
  {
    name: 'Hola Restaurante',
    rating: 4.2,
    reviews: 2004,
    street: '290, Citadine Hotel, Rajiv Gandhi Salai (OMR), IT Expressway, Sholinganallur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 80156 24395',
    category: 'Chinese restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Hola%20Restaurante&query_place_id=ChIJ2ehJI39cUjoREnIzajWZUMs',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 2.2,
    projectType: 'Multi-Cuisine Online Reservation & Mobile App',
  },
  {
    name: 'Lepcha Restaurant, The taste of Darjeeling',
    rating: 4.7,
    reviews: 580,
    street: '3/323',
    city: 'Thoraipakkam',
    state: 'Tamil Nadu',
    phone: '+91 63828 59179',
    category: 'Chinese restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Lepcha%20Restaurant%2C%20The%20taste%20of%20Darjeeling&query_place_id=ChIJ4dBNDIZdUjoRLffPK09VSCo',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.3,
    projectType: 'Authentic Tibetan & Darjeeling Cuisine Web Menu',
  },
  {
    name: 'Sri Supriya Andhra Restaurant',
    rating: 3.8,
    reviews: 1677,
    street: '5/391, Rajiv Gandhi Salai',
    city: 'Thoraipakkam, Chennai',
    state: 'Tamil Nadu',
    phone: '+91 93459 59799',
    category: 'Andhra restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Sri%20Supriya%20Andhra%20Restaurant&query_place_id=ChIJQ3dZvlhcUjoRAi9jpuQM3tU',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.6,
    projectType: 'Andhra Meals Online Ordering System',
  },
  {
    name: 'Mahitha Andhra Restaurant',
    rating: 3.7,
    reviews: 93,
    street: 'dollar stop, 68, Lal Bahadur Shastri St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 97909 80621',
    category: 'Andhra restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Mahitha%20Andhra%20Restaurant&query_place_id=ChIJwwTKHEhdUjoRQg-y957zXOk',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.75,
    projectType: 'Direct WhatsApp Ordering Web Menu',
  },
  {
    name: 'ANDHRA CHILLIES RESTAURANT',
    rating: 3.8,
    reviews: 174,
    street: 'No:15/1 Perumbakkam main road, near sholinganallur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 87784 50770',
    category: 'Biryani restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=ANDHRA%20CHILLIES%20RESTAURANT&query_place_id=ChIJac48q2NcUjoR_gzVVp5n4mo',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.1,
    projectType: 'Biryani Delivery & Catering Booking Site',
  },
  {
    name: 'Appuchi Restaurant',
    rating: 3.7,
    reviews: 204,
    street: 'OMR Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 98844 41415',
    category: 'Chettinad restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Appuchi%20Restaurant&query_place_id=ChIJxZYaBs5dUjoRb6-yUpd0GDg',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.9,
    projectType: 'Traditional Chettinad Restaurant Website',
  },
  {
    name: 'Al Arab Restaurant',
    rating: 4.2,
    reviews: 191,
    street: 'No:1, 91, East Coast Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 88381 39006',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Al%20Arab%20Restaurant&query_place_id=ChIJkzS27a5dUjoRUpEiMVmPn2s',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.4,
    projectType: 'Arabian Mandi & Grill Ordering Web App',
  },
  {
    name: 'Karthika construction',
    rating: 4.8,
    reviews: 6,
    street: '8th Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Karthika%20construction&query_place_id=ChIJ4SF7pyFdUjoRgihZAOHj9_s',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.6,
    projectType: 'Contractor Services & Projects Portfolio',
  },
  {
    name: 'CMR CONSTRUCTION',
    rating: 5.0,
    reviews: 1,
    street: '3rd Cross St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 99625 29503',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=CMR%20CONSTRUCTION&query_place_id=ChIJW7bJETZcUjoR11M4dw7Gq0c',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.75,
    projectType: 'Commercial Construction Portfolio Website',
  },
  {
    name: 'JS ENGINEERING SERVICES AND CONSTRUCTION',
    rating: 5.0,
    reviews: 8,
    street: 'RAMANIYAM JAGGANATH, SIVASWAMY AVENUE, MGR Salai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 89394 73434',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=JS%20ENGINEERING%20SERVICES%20AND%20CONSTRUCTION&query_place_id=ChIJj8vPs0ldUjoRkKBtD2l2kiI',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.6,
    projectType: 'Engineering Services Web Portal & RFQ System',
  },
  {
    name: 'N.V Construction & Builder',
    rating: 4.0,
    reviews: 3,
    street: '2/135',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 98403 66462',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=N.V%20Construction%20%26%20Builder&query_place_id=ChIJyWyxP6NbUjoRkcsXvt4oLio',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.8,
    projectType: 'Residential Builder Gallery & Testimonials Site',
  },
  {
    name: 'JP Construction',
    rating: 4.0,
    reviews: 4,
    street: '391, Village High Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=JP%20Construction&query_place_id=ChIJ9UqBhMpbUjoRd4S02EGv4lI',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.55,
    projectType: 'Builder Portfolio & Client Inquiry Page',
  },
  {
    name: 'Two square construction',
    rating: 4.0,
    reviews: 2,
    street: 'no 79, saya company salai, 26th St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: null,
    category: 'Home builder',
    url: 'https://www.google.com/maps/search/?api=1&query=Two%20square%20construction&query_place_id=ChIJtyNBpI1dUjoRfbLEI8h8DIs',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.6,
    projectType: 'Modern Home Builder Showcase Website',
  },
  {
    name: 'SRI SAIBABA CONSTRUCTION',
    rating: 5.0,
    reviews: 1,
    street: 'Bajanai Koil St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 86108 40644',
    category: 'Civil engineering company',
    url: 'https://www.google.com/maps/search/?api=1&query=SRI%20SAIBABA%20CONSTRUCTION&query_place_id=ChIJgXmKWc5dUjoRmoJbaEHsEEs',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.7,
    projectType: 'Civil Engineering Corporate Website',
  },
  {
    name: 'Quality Inn Restaurant',
    rating: 3.4,
    reviews: 86,
    street: '146 D 4th Avenue, 8th Ave Seashore Town',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 82207 70694',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Quality%20Inn%20Restaurant&query_place_id=ChIJn4DvwjZbUjoRJXO1wnE0dYo',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.9,
    projectType: 'Seaside Dining Website & Table Booking',
  },
  {
    name: 'The Bridge Restaurant',
    rating: 4.3,
    reviews: 15,
    street: 'The Clarks Inn, MRK Arcade, 200 Feet Radial Rd',
    city: 'Thoraipakkam',
    state: 'Tamil Nadu',
    phone: '+91 99402 11223',
    category: 'Buffet restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=The%20Bridge%20Restaurant&query_place_id=ChIJ3VylcApdUjoREz0AX9VrgBg',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 1.1,
    projectType: 'Hotel Buffet Showcase & Pre-Booking Web App',
  },
  {
    name: "Veera's Restaurant",
    rating: 4.4,
    reviews: 45,
    street: 'Street Number 3, opposite to BALAJI DENTAL COLLEGE',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 99949 99056',
    category: 'Chinese restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Veera%27s%20Restaurant&query_place_id=ChIJzXHsww1dUjoRAFF2YzvlEJg',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.75,
    projectType: 'College-Zone Fast Food QR Menu & WhatsApp App',
  },
  {
    name: 'HOT KITCHEN RESTAURANT ECR',
    rating: 3.6,
    reviews: 860,
    street: '78 & 79, East Coast Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 98403 33336',
    category: 'Chettinad restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=HOT%20KITCHEN%20RESTAURANT%20ECR&query_place_id=ChIJNYWlz-dcUjoRhZIZW-dpgMI',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.5,
    projectType: 'Highway Restaurant Online Ordering & Drive-thru Portal',
  },
  {
    name: 'Quality-Inn Restaurant',
    rating: 3.9,
    reviews: 35,
    street: '41 & 42, SH 49',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 89396 22667',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Quality-Inn%20Restaurant&query_place_id=ChIJ7Vclzc1dUjoRJc1CTiBlBtI',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.85,
    projectType: 'Casual Dining Web Menu & Location Landing Page',
  },
  {
    name: 'Zeeshan Restaurant Perungudi',
    rating: 3.7,
    reviews: 2486,
    street: 'OMR Service Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 73959 22999',
    category: 'Hyderabadi restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Zeeshan%20Restaurant%20Perungudi&query_place_id=ChIJEflUuhNdUjoRtqSCQZn5m30',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 2.4,
    projectType: 'Hyderabadi Biryani Chain Custom Ordering Mobile App',
  },
  {
    name: 'Chennai 100 Restaurant',
    rating: 4.0,
    reviews: 112,
    street: 'Shanmuga Complex, Velachery Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 73959 59796',
    category: 'Fast food restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Chennai%20100%20Restaurant&query_place_id=ChIJFwOBDLJdUjoR59O8-cFpCLQ',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.9,
    projectType: 'Fast Food Quick Order Mobile Web App',
  },
  {
    name: 'Fine Dine Restaurant',
    rating: 2.8,
    reviews: 9,
    street: 'No 2/37 First Street , Ma.Po.Si Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 89394 33229',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Fine%20Dine%20Restaurant&query_place_id=ChIJP-PByrhZUjoRdlbpO8E_cno',
    priority: 'COLD',
    stage: 'NEW',
    budgetLakhs: 0.6,
    projectType: 'Local Dining Website & Digital Presence Package',
  },
  {
    name: 'Sh Restaurant',
    rating: 4.4,
    reviews: 20,
    street: '5, Madha Koil St',
    city: 'Thoraipakkam',
    state: 'Tamil Nadu',
    phone: '+91 79048 54497',
    category: 'Indian restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Sh%20Restaurant&query_place_id=ChIJbY8_1lRdUjoRoOZTnjOmH6U',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.7,
    projectType: 'Neighborhood Restaurant Menu & WhatsApp Ordering',
  },
  {
    name: 'Ulavacharu Restaurant Taste of Andhra',
    rating: 3.5,
    reviews: 11,
    street: 'Near Radial Rd Junction',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 87784 50770',
    category: 'Andhra restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Ulavacharu%20Restaurant%20Taste%20of%20Andhra&query_place_id=ChIJZa1rfa1dUjoRZBl8e9a1dcA',
    priority: 'WARM',
    stage: 'NEW',
    budgetLakhs: 0.8,
    projectType: 'Andhra Specialties Showcase & Online Booking Web Page',
  },
  {
    name: 'Al Basheer Restaurant',
    rating: 3.8,
    reviews: 233,
    street: 'V6PH+292, Ponniamman Koil 1st St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 99945 95853',
    category: 'Biryani restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Al%20Basheer%20Restaurant&query_place_id=ChIJF5aPBElbUjoRZevXaLXNsEo',
    priority: 'HOT',
    stage: 'NEW',
    budgetLakhs: 1.3,
    projectType: 'Direct Customer Food Ordering Web App & Delivery System',
  },
];

async function main() {
  console.log('🚀 Seeding 50 DND Studio Local Business Leads...');

  // Fetch or upsert Principals
  const passwordHash = await bcrypt.hash('password123', 12);

  const nirmal = await prisma.user.upsert({
    where: { email: 'nirmalkumar00727@gmail.com' },
    update: { name: 'Nirmal kumar N', role: 'ADMIN', initials: 'N' },
    create: { email: 'nirmalkumar00727@gmail.com', password: passwordHash, name: 'Nirmal kumar N', role: 'ADMIN', initials: 'N' },
  });

  const gayathri = await prisma.user.upsert({
    where: { email: 'gayathrideva2007@gmail.com' },
    update: { name: 'Gayathri Deva', role: 'PRINCIPAL', initials: 'GD' },
    create: { email: 'gayathrideva2007@gmail.com', password: passwordHash, name: 'Gayathri Deva', role: 'PRINCIPAL', initials: 'GD' },
  });

  // Clear existing leads
  await prisma.activity.deleteMany({});
  await prisma.note.deleteMany({});
  await prisma.meeting.deleteMany({});
  await prisma.fileAsset.deleteMany({});
  await prisma.proposal.deleteMany({});
  await prisma.notification.deleteMany({});
  await prisma.lead.deleteMany({});

  console.log('🧹 Cleaned previous leads for fresh seed.');

  const owners = [nirmal, gayathri];

  for (let i = 0; i < RAW_LEADS_DATA.length; i++) {
    const item = RAW_LEADS_DATA[i];
    const owner = owners[i % owners.length];
    const leadCode = `DND-${String(i + 1).padStart(3, '0')}`;

    const winProb =
      item.stage === 'WON' ? 100 :
      item.stage === 'NEGOTIATION' ? 85 :
      item.stage === 'PROPOSAL' ? 70 :
      item.stage === 'MEETING' ? 50 :
      item.stage === 'CONTACTED' ? 30 : 15;

    const ratingText = item.rating ? `⭐ ${item.rating}` : 'New Listing';
    const reviewsText = item.reviews ? `${item.reviews} reviews` : 'Fresh Prospect';

    const tags = [
      item.category,
      item.rating ? `${item.rating}★` : null,
      item.reviews ? `${item.reviews} reviews` : null,
      'Google Maps Lead',
      item.city.split(',')[0].trim(),
    ].filter(Boolean);

    const description = `📍 Google Maps Listing: ${item.name} (${item.category})\n` +
      `★ Rating: ${ratingText} (${reviewsText})\n` +
      `🏢 Address: ${item.street ? item.street + ', ' : ''}${item.city}, ${item.state}\n` +
      `🌐 Maps Link: ${item.url}\n` +
      `💡 DND Studio Pitch: ${item.projectType}. Build custom high-converting web and mobile presence to grow direct sales and automate inquiries.`;

    const lead = await prisma.lead.create({
      data: {
        id: leadCode,
        name: item.name,
        projectType: item.projectType,
        projectDescription: description,
        location: `${item.city}, Tamil Nadu`,
        budgetLakhs: item.budgetLakhs,
        source: 'Google',
        priority: item.priority as any,
        phone: item.phone,
        email: `info@${item.name.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 15)}.com`,
        ownerId: owner.id,
        winProbability: 15,
        tags: JSON.stringify(tags),
        stage: 'NEW',
        stageChangedAt: new Date(),
      },
    });
  }

  console.log(`✅ Successfully seeded ${RAW_LEADS_DATA.length} leads for DND Studio!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
