import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

export const FRESH_LEADS_DATA = [
  {
    serialNo: 1,
    name: 'K.M constructions',
    rating: 5.0,
    reviews: 30,
    address: 'No 2, 10th Cross St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '8778273957',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=K.M%20constructions&query_place_id=ChIJmxzHDUJhUjoRvPcbwEQhDoQ',
    priority: 'HOT',
    budgetLakhs: 65,
    projectType: 'Turnkey Architecture & Construction',
  },
  {
    serialNo: 2,
    name: 'Rajalakshmi Constructions',
    rating: 5.0,
    reviews: 10,
    address: '148, Radha Ave Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9941525262',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Rajalakshmi%20Constructions&query_place_id=ChIJa_W7cjdhUjoR0uIMhl1Q3hk',
    priority: 'HOT',
    budgetLakhs: 55,
    projectType: 'Turnkey Architecture & Construction',
  },
  {
    serialNo: 3,
    name: 'SPERANZA CONSTRUCTIONS, RENOVATION AND INTERIORS.',
    rating: 5.0,
    reviews: 33,
    address: '2, First street, C.D.N. Nagar Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9940888456',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=SPERANZA%20CONSTRUCTIONS%2C%20RENOVATION%20AND%20INTERIORS.&query_place_id=ChIJB5uofZJhUjoRj7EnwRWcQWk',
    priority: 'HOT',
    budgetLakhs: 70,
    projectType: 'Luxury Interior Renovation & Architecture',
  },
  {
    serialNo: 4,
    name: 'RJ Constructions',
    rating: 3.9,
    reviews: 8,
    address: '1st Cross Street, 2nd Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '8248791229',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=RJ%20Constructions&query_place_id=ChIJO1LpCG9hUjoRUI3XwwuGUfk',
    priority: 'WARM',
    budgetLakhs: 45,
    projectType: 'Turnkey Architecture & Construction',
  },
  {
    serialNo: 5,
    name: 'Blessed builders',
    rating: 5.0,
    reviews: 5,
    address: 'Jayaram nagar, 1st St',
    city: 'Vanagaram',
    state: 'Tamil Nadu',
    phone: '9710618807',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Blessed%20builders&query_place_id=ChIJwxgxaWVhUjoRMxe01Wer9Kc',
    priority: 'HOT',
    budgetLakhs: 50,
    projectType: 'Turnkey Architecture & Construction',
  },
  {
    serialNo: 6,
    name: 'Tharun Construction',
    rating: 4.2,
    reviews: 9,
    address: '2nd Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9087888402',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Tharun%20Construction&query_place_id=ChIJKdPhcTRhUjoRJgXxdEb3iy0',
    priority: 'WARM',
    budgetLakhs: 48,
    projectType: 'Turnkey Architecture & Construction',
  },
  {
    serialNo: 7,
    name: 'R.K.CONSTRUCTION',
    rating: 3.8,
    reviews: 4,
    address: 'NO.5, R.K.BAVANAM, 7TH STREET IYYAPPA NAGAR, MADURAVOYAL',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9840324264',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=R.K.CONSTRUCTION&query_place_id=ChIJAYR7PlZhUjoRmyBs4uV7pok',
    priority: 'WARM',
    budgetLakhs: 52,
    projectType: 'Turnkey Architecture & Construction',
  },
  {
    serialNo: 8,
    name: 'Krishna Builders',
    rating: 5.0,
    reviews: 1,
    address: '36, 1st Cross St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9840073239',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Krishna%20Builders&query_place_id=ChIJn9iDHT9hUjoRKDDFnvRJcj0',
    priority: 'HOT',
    budgetLakhs: 60,
    projectType: 'Turnkey Architecture & Construction',
  },
  {
    serialNo: 9,
    name: 'Blue Well Restaurant',
    rating: 4.9,
    reviews: 112,
    address: '32, Alapakkam Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9360931010',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Blue%20Well%20Restaurant&query_place_id=ChIJWdUsFONhUjoRr9bOsUc3-uM',
    priority: 'HOT',
    budgetLakhs: 35,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 10,
    name: "The Madras cafe's",
    rating: 4.9,
    reviews: 18,
    address: '6, Chokkanathar St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '7530001484',
    category: 'Family restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=The%20Madras%20cafe%27s&query_place_id=ChIJ23o7SQBhUjoRNwIYZaoPR9Q',
    priority: 'HOT',
    budgetLakhs: 28,
    projectType: 'Commercial Dining & Cafe Design',
  },
  {
    serialNo: 11,
    name: 'House of Tandoor',
    rating: 4.6,
    reviews: 346,
    address: 'Guru Brindhavan Garden, Vanagaram-Ambattur Rd',
    city: 'Adayalampattu',
    state: 'Tamil Nadu',
    phone: '9884600365',
    category: 'Family restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=House%20of%20Tandoor&query_place_id=ChIJizLrGgBhUjoRahc-AapS51M',
    priority: 'HOT',
    budgetLakhs: 40,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 12,
    name: "SON'S Restaurant",
    rating: 4.1,
    reviews: 930,
    address: 'No 21',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '7358290985',
    category: 'Fine dining restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=SON%27S%20Restaurant&query_place_id=ChIJ20xB4NxhUjoRtax2mu6Tp-k',
    priority: 'WARM',
    budgetLakhs: 45,
    projectType: 'Fine Dining & Hospitality Interior',
  },
  {
    serialNo: 13,
    name: 'Swarnamukhii Cloud Kitchen',
    rating: 4.5,
    reviews: 76,
    address: 'No14, Velan Nagar 9th St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9566111646',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Swarnamukhii%20Cloud%20Kitchen&query_place_id=ChIJZVqOcL1hUjoRuhRjkoGXVYE',
    priority: 'HOT',
    budgetLakhs: 25,
    projectType: 'Commercial Cloud Kitchen Fitout',
  },
  {
    serialNo: 14,
    name: "Tummie Filler's Restaurant",
    rating: 4.5,
    reviews: 42,
    address: '3536+MCG, Chokkalingam Naicker 5th St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '8148018613',
    category: 'Family restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Tummie%20Filler%27s%20Restaurant&query_place_id=ChIJzbUb1v5hUjoRvIhCgLJE6xA',
    priority: 'HOT',
    budgetLakhs: 30,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 15,
    name: 'FAMILY RESTAURANT',
    rating: 5.0,
    reviews: 1,
    address: 'Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '8459946120',
    category: 'Family restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=FAMILY%20RESTAURANT&query_place_id=ChIJFek8AnJhUjoRotAFtu5L5o4',
    priority: 'HOT',
    budgetLakhs: 25,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 16,
    name: 'Resto Corner',
    rating: 5.0,
    reviews: 10,
    address: 'Plot No : 14, Abirami Nagar 4th St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9962212724',
    category: 'Cafe',
    url: 'https://www.google.com/maps/search/?api=1&query=Resto%20Corner&query_place_id=ChIJzfa_6BxhUjoRGfNyiXCEfMA',
    priority: 'HOT',
    budgetLakhs: 22,
    projectType: 'Cafe & Commercial Interior',
  },
  {
    serialNo: 17,
    name: 'Toast And Talk',
    rating: 4.7,
    reviews: 3,
    address: 'The Schram Academy 2',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '8122907708',
    category: 'Restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Toast%20And%20Talk&query_place_id=ChIJgbNhAD9hUjoR9N-ZsskJ8T4',
    priority: 'HOT',
    budgetLakhs: 26,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 18,
    name: 'MADURAVOYAL PANDIAN MESS',
    rating: 4.8,
    reviews: 1444,
    address: '132, Alapakkam Main Rd, opp. meenakshi school',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9962566625',
    category: 'Seafood restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=MADURAVOYAL%20PANDIAN%20MESS&query_place_id=ChIJuRDRe9lhUjoRVS4bxGPiXuc',
    priority: 'HOT',
    budgetLakhs: 38,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 19,
    name: 'Arabian Home Food',
    rating: 4.3,
    reviews: 40,
    address: '123, Mettukuppam Rd, near EB Office',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9884880570',
    category: 'Arab restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Arabian%20Home%20Food&query_place_id=ChIJcxswhAZhUjoRxGPTpuvDLuU',
    priority: 'WARM',
    budgetLakhs: 28,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 20,
    name: 'Kadher Bhai Biryani Maduravoyal (K2B)',
    rating: 4.0,
    reviews: 1387,
    address: '3578+RRM, 4, Sannathi St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '7397377725',
    category: 'Biryani restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Kadher%20Bhai%20Biryani%20Maduravoyal%20(K2B)&query_place_id=ChIJ7VW4MMJhUjoR030-fphoxWU',
    priority: 'WARM',
    budgetLakhs: 35,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 21,
    name: 'BIRIYANI CHOWK',
    rating: 4.2,
    reviews: 29,
    address: 'Maduravoyal #15, MCK Layout, Bypass, Service Rd',
    city: 'Adayalampattu, Chennai',
    state: 'Tamil Nadu',
    phone: '8438184010',
    category: 'Family restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=BIRIYANI%20CHOWK&query_place_id=ChIJO0Eg8MBhUjoRJJqJNoNgKGk',
    priority: 'WARM',
    budgetLakhs: 30,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 22,
    name: 'Crown Brick Construction',
    rating: 4.0,
    reviews: 5,
    address: '171, Poonamallee High Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9600426219',
    category: 'Construction company',
    url: 'https://www.google.com/maps/search/?api=1&query=Crown%20Brick%20Construction&query_place_id=ChIJwxdv7l5hUjoRwSaMeueaiLs',
    priority: 'WARM',
    budgetLakhs: 50,
    projectType: 'Turnkey Architecture & Construction',
  },
  {
    serialNo: 23,
    name: 'RIVER SAND M SAND P SAND AVAILABLE',
    rating: 5.0,
    reviews: 38,
    address: 'Muthumari Amman Kovil street New subramanian Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9941966474',
    category: 'Construction material wholesaler',
    url: 'https://www.google.com/maps/search/?api=1&query=RIVER%20SAND%20M%20SAND%20P%20SAND%20AVAILABLE&query_place_id=ChIJNfMH_DxhUjoR93KPadF6PtU',
    priority: 'HOT',
    budgetLakhs: 40,
    projectType: 'Industrial Infrastructure & Supply',
  },
  {
    serialNo: 24,
    name: '3Star Infra Engineering.',
    rating: 5.0,
    reviews: 4,
    address: 'Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '7448633339',
    category: 'Construction machine rental service',
    url: 'https://www.google.com/maps/search/?api=1&query=3Star%20Infra%20Engineering.&query_place_id=ChIJjzfOw01hUjoRXWMjB4wYhng',
    priority: 'HOT',
    budgetLakhs: 60,
    projectType: 'Industrial Infrastructure & Heavy Engineering',
  },
  {
    serialNo: 25,
    name: 'Salem RR Biryani - Maduravoyal Branch',
    rating: 3.3,
    reviews: 2324,
    address: 'Post Office stopping, Mumbai Hwy',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '4429492000',
    category: 'Biryani restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Salem%20RR%20Biryani%20-%20Maduravoyal%20Branch&query_place_id=ChIJvWh76nZhUjoRnf4eZ0Pt1LQ',
    priority: 'WARM',
    budgetLakhs: 45,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 26,
    name: '2 Idly 1 Vadai Restaurant',
    rating: 4.0,
    reviews: 1015,
    address: '3528+GG9, Alapakkam Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '7401654053',
    category: 'South Indian restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=2%20Idly%201%20Vadai%20Restaurant&query_place_id=ChIJHUxSftlhUjoRVYLMzPXfxmw',
    priority: 'WARM',
    budgetLakhs: 30,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 27,
    name: 'Hotel Pandian',
    rating: 3.7,
    reviews: 2793,
    address: 'No1/10 Poonamallee High Road, Ganapathy Nagar, Maduravoyal',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9176558648',
    category: 'South Indian restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Hotel%20Pandian&query_place_id=ChIJEaJS_3FhUjoRtX0_p_Dv0b4',
    priority: 'WARM',
    budgetLakhs: 35,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 28,
    name: 'Sri Balavignesh Bhavan',
    rating: 3.8,
    reviews: 522,
    address: 'Kanchipuram - Chennai Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '4423860491',
    category: 'South Indian restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Sri%20Balavignesh%20Bhavan&query_place_id=ChIJH3llAHJhUjoRqeeUAqMODG4',
    priority: 'WARM',
    budgetLakhs: 28,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 29,
    name: 'Hotel Shenbagaa Bhavan',
    rating: 3.9,
    reviews: 277,
    address: '340, Poonamallee High Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '8939471378',
    category: 'Vegan restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Hotel%20Shenbagaa%20Bhavan&query_place_id=ChIJMTNBAENhUjoR6jAc8TuNKCo',
    priority: 'HOT',
    budgetLakhs: 32,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 30,
    name: 'New Hyderabad Biriyani',
    rating: 3.7,
    reviews: 61,
    address: 'No.1, 98, Poonamallee High Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '4424761776',
    category: 'Hyderabadi restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=New%20Hyderabad%20Biriyani&query_place_id=ChIJISLrLqthUjoRN5bNTyXtLzY',
    priority: 'WARM',
    budgetLakhs: 25,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 31,
    name: 'Bismillah Biriyani Stall and tiffen centre',
    rating: 5.0,
    reviews: 2,
    address: 'Kkr ent hospital, 2nd Main Rd, opposite mmda',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9342045120',
    category: 'Tiffin center',
    url: 'https://www.google.com/maps/search/?api=1&query=Bismillah%20Biriyani%20Stall%20and%20tiffen%20centre&query_place_id=ChIJDRVTJbhhUjoRB2CLuXKPxdk',
    priority: 'HOT',
    budgetLakhs: 20,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 32,
    name: 'Naadan thattu',
    rating: 3.0,
    reviews: 2,
    address: 'No 48 a, 5th St',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '8848991423',
    category: 'Kerala restaurant',
    url: 'https://www.google.com/maps/search/?api=1&query=Naadan%20thattu&query_place_id=ChIJbdunz9xhUjoR3WrqF5yfVJs',
    priority: 'COLD',
    budgetLakhs: 18,
    projectType: 'Commercial Dining & Hospitality Fitout',
  },
  {
    serialNo: 33,
    name: 'Roopa Rekha bakery',
    rating: 4.0,
    reviews: 25,
    address: '13, Shridevikuppam Main Rd',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '9962900186',
    category: 'Bakery',
    url: 'https://www.google.com/maps/search/?api=1&query=Roopa%20Rekha%20bakery&query_place_id=ChIJO0YttTBhUjoRDfaXWXvXQf8',
    priority: 'WARM',
    budgetLakhs: 22,
    projectType: 'Retail Bakery & Cafe Design',
  },
];

async function main() {
  console.log('🚀 Seeding 33 Fresh Leads starting at DND-001...');

  const passwordHash = await bcrypt.hash('password123', 12);

  const nirmal = await prisma.user.upsert({
    where: { email: 'nirmalkumar00727@gmail.com' },
    update: { name: 'Nirmal kumar N', role: 'ADMIN', initials: 'N' },
    create: { email: 'nirmalkumar00727@gmail.com', password: passwordHash, name: 'Nirmal kumar N', role: 'ADMIN', initials: 'N' },
  });

  const gayathri = await prisma.user.upsert({
    where: { email: 'gayathrideva2007@gmail.com' },
    update: { name: 'Gayathri', role: 'PRINCIPAL', initials: 'G' },
    create: { email: 'gayathrideva2007@gmail.com', password: passwordHash, name: 'Gayathri', role: 'PRINCIPAL', initials: 'G' },
  });

  // Clear existing leads and dependent tables
  await prisma.activity.deleteMany({});
  await prisma.note.deleteMany({});
  await prisma.meeting.deleteMany({});
  await prisma.fileAsset.deleteMany({});
  await prisma.proposal.deleteMany({});
  await prisma.notification.deleteMany({});
  await prisma.lead.deleteMany({});

  try {
    await prisma.$executeRawUnsafe(`SELECT setval(pg_get_serial_sequence('leads', 'serialNo'), 1, false);`);
    console.log('Reset sequence to 1');
  } catch (e) {
    console.warn('Could not reset sequence via raw query:', e);
  }

  const owners = [gayathri, nirmal];

  for (let i = 0; i < FRESH_LEADS_DATA.length; i++) {
    const item = FRESH_LEADS_DATA[i];
    const owner = owners[i % owners.length];
    const leadCode = `DND-${String(i + 1).padStart(3, '0')}`;

    const tags = [
      'Fresh Lead',
      item.category,
      item.city,
      item.rating >= 4.5 ? 'Top Rated' : 'Verified',
    ];

    const description = `📍 Google Maps Listing: ${item.name} (${item.category})\n` +
      `★ Rating: ⭐ ${item.rating} (${item.reviews} reviews)\n` +
      `🏢 Address: ${item.address ? item.address + ', ' : ''}${item.city}, ${item.state}\n` +
      `🌐 Maps Link: ${item.url}\n` +
      `💡 Project: ${item.projectType}`;

    const winProb = item.priority === 'HOT' ? 75 : item.priority === 'WARM' ? 50 : 30;

    await prisma.lead.create({
      data: {
        id: leadCode,
        serialNo: item.serialNo,
        name: item.name,
        projectType: item.projectType,
        projectDescription: description,
        location: `${item.address ? item.address + ', ' : ''}${item.city}, ${item.state}`,
        budgetLakhs: item.budgetLakhs,
        source: 'Google',
        priority: item.priority as any,
        phone: item.phone,
        email: `contact@${item.name.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 15)}.in`,
        ownerId: owner.id,
        winProbability: winProb,
        tags: JSON.stringify(tags),
        stage: 'NEW',
        stageChangedAt: new Date(),
      },
    });

    console.log(`Created lead #${item.serialNo}: ${item.name} (${leadCode})`);
  }

  console.log(`✅ Successfully seeded all ${FRESH_LEADS_DATA.length} fresh leads starting at DND-001!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
